### ISSUE TITLE
Telemetry Core -- Serial1 or Serial for Rasberry pi - HUD connection

### ISSUE THREAD

**Issue by tovedetered** [uvmaero/CleanSpeed_6.0_Firmware#3]
On line 571 of the Telemetry core:

// HUD update
      Serial.write((uint8_t *)&telemetryCoreData, sizeof(telemetryCoreData));

However, above on line 362

// --------------------- initialize RPi Connection -------------------------- //
  Serial1.begin(9600, 134217756U, RPI_RX_PIN, RPI_TX_PIN);
  setup.rpiComActive = true;

Is Serial1 the rasperry pi, and therefore the HUD?

Proposed fix, using an alias, such as HUD for the hud and DEBUG for the serial to eliminate any confusion

**Comment by dom-gasperini** [comment]
"Serial1" is for the raspberry pi acting as the HUD, go for it

**Comment by tovedetered** [comment]
Pull request is up, PR #4
